public with sharing class Bot_GetRecord {

 
public void someMethod(){

    System.System.debug('This is a test');

    }

public void someMethod2(){

    System.System.debug('This is a test');

    }
    
public void someMethod3(){

    System.System.debug('This is a test');

    }
   
 public void someMethod4(){

    System.System.debug('This is a test');

    }

 public void someMethod6(){

    System.System.debug('This is a test');

    }
       
 public void someMethod5(){

    System.System.debug('This is a test');

    }

     public void someMethod7(){

    System.System.debug('This is a test');

    }
   

    public void someMethod6(){

    System.System.debug('This is a test');

    }
   
}