public with sharing class Bot_PutRecord {
   
 public void someMethod4(){

    System.System.debug('This is a test123');

    }

 
        public void someMethod6(){
 

    System.System.debug('This is a test123');

    }


     
        public void someMethod7(){
 

    System.System.debug('This sdfdsfsdfdsis a test');

    }

         
        public void someMethod8(){
 

    System.System.debug('This is a test');

    }
   
}