public with sharing class PaymentInterfa {

public void someMethod(){

    System.System.debug('This is a test');

    }


    public void secondMethod(){

    System.System.debug('This is a test');

    }
   


   public void thirdMethod(){

    System.System.debug('This is a test');



    }

        public void someMethod6(){

    System.System.debug('This is a test');

    }
            public void someMethodwow(){

    System.System.debug('This is a test');

    }

            public void someMethod7(){

    System.System.debug('This is a test');

    }
}